language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-24
    - android-22
    - sys-img-armeabi-v7a-android-22
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi $ANDROID_ABI -c 32M
  - emulator -avd test -no-skin -no-audio -no-window &
  - wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
  - unzip -q android-ndk-r20-linux-x86_64.zip
  - export PATH=$PATH:$PWD/android-ndk-r20

before_script:
  - ./ci/wait_for_emulator.sh

script: ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./ci/release.sh
